"""migracion

Revision ID: 02dc260e8f75
Revises: 
Create Date: 2025-05-19 18:53:32.065351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02dc260e8f75'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Roles',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre_rol', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre_rol')
    )
    op.create_index(op.f('ix_Roles_id_rol'), 'Roles', ['id_rol'], unique=False)
    op.create_table('Usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('contrasena', sa.String(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_Usuarios_email'), 'Usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_Usuarios_id_usuario'), 'Usuarios', ['id_usuario'], unique=False)
    op.create_table('Citas',
    sa.Column('id_cita', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('id_psicologo', sa.Integer(), nullable=False),
    sa.Column('fecha_hora_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_hora_fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modalidad', sa.String(length=20), nullable=False),
    sa.Column('fecha_solicitud', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_confirmacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_cancelacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_estudiante'], ['Usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_psicologo'], ['Usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_cita')
    )
    op.create_index(op.f('ix_Citas_id_cita'), 'Citas', ['id_cita'], unique=False)
    op.create_table('DisponibilidadPsicologo',
    sa.Column('id_disponibilidad', sa.Integer(), nullable=False),
    sa.Column('id_psicologo', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.String(length=10), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['id_psicologo'], ['Usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_disponibilidad')
    )
    op.create_index(op.f('ix_DisponibilidadPsicologo_id_disponibilidad'), 'DisponibilidadPsicologo', ['id_disponibilidad'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_DisponibilidadPsicologo_id_disponibilidad'), table_name='DisponibilidadPsicologo')
    op.drop_table('DisponibilidadPsicologo')
    op.drop_index(op.f('ix_Citas_id_cita'), table_name='Citas')
    op.drop_table('Citas')
    op.drop_index(op.f('ix_Usuarios_id_usuario'), table_name='Usuarios')
    op.drop_index(op.f('ix_Usuarios_email'), table_name='Usuarios')
    op.drop_table('Usuarios')
    op.drop_index(op.f('ix_Roles_id_rol'), table_name='Roles')
    op.drop_table('Roles')
    # ### end Alembic commands ###
