"""add observaciones table

Revision ID: 3868d0d804c7
Revises: noti1
Create Date: 2025-05-26 17:10:19.000926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3868d0d804c7'
down_revision: Union[str, None] = 'noti1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Observaciones',
    sa.Column('id_observacion', sa.Integer(), nullable=False),
    sa.Column('id_cita', sa.Integer(), nullable=False),
    sa.Column('id_psicologo', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_cita'], ['Citas.id_cita'], ),
    sa.ForeignKeyConstraint(['id_psicologo'], ['Usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_observacion')
    )
    op.create_index(op.f('ix_Observaciones_id_observacion'), 'Observaciones', ['id_observacion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Observaciones_id_observacion'), table_name='Observaciones')
    op.drop_table('Observaciones')
    # ### end Alembic commands ###
