"""add id_cita to DisponibilidadPsicologo

Revision ID: 81bd4af25701
Revises: 02dc260e8f75
Create Date: 2025-05-19 19:27:49.253154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81bd4af25701'
down_revision: Union[str, None] = '02dc260e8f75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DisponibilidadPsicologo', sa.Column('id_cita', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'DisponibilidadPsicologo', 'Citas', ['id_cita'], ['id_cita'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'DisponibilidadPsicologo', type_='foreignkey')
    op.drop_column('DisponibilidadPsicologo', 'id_cita')
    # ### end Alembic commands ###
